version: '3'

services:
  app:
    restart: always
    container_name: scout-manager
    build: .
    # map the local (host) directories to their container counterparts
    # to support live-syncing
    volumes:
      - ./scout_manager:/app/scout-manager
    ports:
      - "${PORT:-8000}:8000"
    environment:
      ENV: localdev
      REMOTE_USER: ${REMOTE_USER:-javerage}
