version: '3'

services:
  app:
    restart: always
    build: .
    # map the local (host) directories to their container counterparts
    # to support live-syncing
    volumes:
      - ./sampleproj:/app/sampleproj
      - ./scout_manager:/app/scout_manager
    ports:
      - "${PORT:-8000}:8000"
    command: bash -c "python manage.py migrate --settings=sampleproj.settings.local && REMOTE_USER=${REMOTE_USER:-javerage} python manage.py runserver 0.0.0.0:8000 --settings=sampleproj.settings.local"
