ingress:
  enabled: true
  tls:
    scout-manager:
      secretName: test.scout-manager.uw.edu-ingress-cert
      hosts:
        - test.scout-manager.uw.edu
  hosts:
    scout-manager:
      host: test.scout-manager.uw.edu
      paths:
        - "/"
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt
    nginx.ingress.kubernetes.io/ssl-ciphers: "ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:DHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES256-GCM-SHA384:ECDHE-RSA-AES128-SHA256"
    nginx.ingress.kubernetes.io/client-body-buffer-size: "16K"
    nginx.ingress.kubernetes.io/permanent-redirect: https://test.scout-manager.uw.edu
lifecycle:
  enabled: true
  preStop:
    enabled: true
affinity:
   podsSpanNodes: true
readiness:
  enabled: true
securityPolicy:
  enabled: true
externalService:
  enabled: true
  name: scout-manager-db-service
  type: ClusterIP
  serviceAddress: 172.18.0.37   # CHANGE TO MATCH
  servicePort: 3306
database:
  engine: mysql
  name: scout_manager_test
  hostname: scout-manager-db-service
  secretName: test.scout-manager.uw.edu-sql-secrets
repo: scout-manager
instance: test
image:
  repository: gcr.io/uwit-mci-axdd/scout-manager
  tag: IMAGE_TAG
memcached:
  enabled: false
gcsCredentials:
  mounted: true
  secretName: test.scout-manager.uw.edu-gc-service-credentials
cronjob:
  enabled: false
certs:
  mounted: true
  certPath: /certs/test.scout-manager.uw.edu-uwca.cert
  keyPath: /certs/test.scout-manager.uw.edu-uwca.key
  secretName: test.scout-manager.uw.edu-uwca-certs
environmentVariables:
  - name: AUTH
    value: SAML
  - name: CLUSTER_CNAME
    value: test.scout-manager.uw.edu
  - name: ENV
    value: test
  - name: RESTCLIENTS_SPOTSEEKER_DAO_CLASS
    value: Mock
  - name: RESTCLIENTS_SPOTSEEKER_HOST
    value: https://test.spotseeker.uw.edu
  - name: SAML_ENTITY_ID
    value: https://test.scout-manager.uw.edu/saml2
  - name: WEBSERVER
    value: nginx
externalSecrets:
  enabled: true
  secrets:
    - name: test.scout-manager.uw.edu-secrets
      externalKey: axdd/kv/data/scout-manager/test/secrets
      data:
        - name: authz-group-backend
          property: authz-group-backend
        - name: django-secret
          property: django-secret
        - name: manager-superuser-group
          property: manager-superuser-group
        - name: oauth-user
          property: oauth-user
        - name: spotseeker-oauth-key
          property: spotseeker-oauth-key
        - name: spotseeker-oauth-secret
          property: spotseeker-oauth-secret
        - name: storage-bucket-name
          property: storage-bucket-name
        - name: storage-project-id
          property: storage-project-id
        - name: userservice-admin-group
          property: userservice-admin-group
    - name: test.scout-manager.uw.edu-sql-secrets
      externalKey: axdd/kv/data/scout-manager/test/sql-secrets
      data:
        - name: username
          property: username
        - name: password
          property: password
    - name: test.scout-manager.uw.edu-uwca-certs
      externalKey: axdd/kv/data/scout-manager/test/uwca-certs
      data:
        - name: test.scout-manager.uw.edu-uwca.cert
          property: test.scout-manager.uw.edu-uwca.cert
        - name: test.scout-manager.uw.edu-uwca.key
          property: test.scout-manager.uw.edu-uwca.key
    - name: test.scout-manager.uw.edu-ic-certs
      externalKey: axdd/kv/data/scout-manager/test/ic-certs
      data:
        - name: test.scout-manager.uw.edu-ic.cert
          property: test.scout-manager.uw.edu-ic.cert
    - name: test.scout-manager.uw.edu-gc-service-credentials
      externalKey: axdd/kv/data/scout-manager/test/gc-service-credentials
      data:
        - name: credentials.json
          property: credentials.json
    - name: test.scout-manager.uw.edu-uw-idp-cert
      externalKey: axdd/kv/data/idp-cert
      data:
        - name: uw-idp-cert
          property: cert
environmentVariablesSecrets:
  authzGroupBackend:
    name: AUTHZ_GROUP_BACKEND
    secretName: test.scout-manager.uw.edu-secrets
    secretKey: authz-group-backend
  djangoSecret:
    name: DJANGO_SECRET
    secretName: test.scout-manager.uw.edu-secrets
    secretKey: django-secret
  managerSuperuserGroup:
    name: MANAGER_SUPERUSER_GROUP
    secretName: test.scout-manager.uw.edu-secrets
    secretKey: manager-superuser-group
  oauthUser:
    name: OAUTH_USER
    secretName: test.scout-manager.uw.edu-secrets
    secretKey: oauth-user
  samlSPCert:
    name: SP_CERT
    secretName: test.scout-manager.uw.edu-ic-cert
    secretKey: test.scout-manager.uw.edu-ic.cert
  samlIDPCert:
    name: IDP_CERT
    secretName: test.scout-manager.uw.edu-uw-idp-cert
    secretKey: uw-idp-cert
  spotseekerOauthKey:
    name: SPOTSEEKER_OAUTH_KEY
    secretName: test.scout-manager.uw.edu-secrets
    secretKey: spotseeker-oauth-key
  spotseekerOauthSecret:
    name: SPOTSEEKER_OAUTH_SECRET
    secretName: test.scout-manager.uw.edu-secrets
    secretKey: spotseeker-oauth-secret
  storageBucketName:
    name: STORAGE_BUCKET_NAME
    secretName: test.scout-manager.uw.edu-secrets
    secretKey: storage-bucket-name
  storageProjectId:
    name: STORAGE_PROJECT_ID
    secretName: test.scout-manager.uw.edu-secrets
    secretKey: storage-project-id
  userserviceAdminGroup:
    name: USERSERVICE_ADMIN_GROUP
    secretName: test.scout-manager.uw.edu-secrets
    secretKey: userservice-admin-group
